spring:
  security:
    user:
      name: user
      password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          format_sql: true
    defer-datasource-initialization: true
  #          show_sql: true

  sql:
    init:
      mode: embedded

logging:
  level:
    org.hibernate.sql: debug

#server:
#  ssl:
#    key-store-type: ${KEY_STORE_TYPE}
#    key-store: ${KEY_STORE}
#    key-store-password: ${KEY_STORE_PASSWORD}


authorization.key: SD9cICjl1e